minimumReleaseAge: 7200 # 60min * 24 * 5
minimumReleaseAgeExclude:

trustPolicy: no-downgrade
trustPolicyExclude:
trustPolicyIgnoreAfter: 43200 # 60min * 24 * 30

blockExoticSubdeps: true

strictDepBuilds: true
